# This file is automatically generated from script.rs
# DO NOT EDIT THIS FILE DIRECTLY

module Regex::Syntax::UnicodeTables::Script
  # ADLAM
  ADLAM = [
    0x1E900_u32..0x1E94B_u32,
    0x1E950_u32..0x1E959_u32,
    0x1E95E_u32..0x1E95F_u32,
  ]

  # AHOM
  AHOM = [
    0x11700_u32..0x1171A_u32,
    0x1171D_u32..0x1172B_u32,
    0x11730_u32..0x11746_u32,
  ]

  # ANATOLIAN HIEROGLYPHS
  ANATOLIAN_HIEROGLYPHS = [
    0x14400_u32..0x14646_u32,
  ]

  # ARABIC
  ARABIC = [
    0x600_u32..0x604_u32,
    0x606_u32..0x60B_u32,
    0x60D_u32..0x61A_u32,
    0x61C_u32..0x61E_u32,
    0x620_u32..0x63F_u32,
    0x641_u32..0x64A_u32,
    0x656_u32..0x66F_u32,
    0x671_u32..0x6DC_u32,
    0x6DE_u32..0x6FF_u32,
    0x750_u32..0x77F_u32,
    0x870_u32..0x88E_u32,
    0x890_u32..0x891_u32,
    0x897_u32..0x8E1_u32,
    0x8E3_u32..0x8FF_u32,
    0xFB50_u32..0xFBC2_u32,
    0xFBD3_u32..0xFD3D_u32,
    0xFD40_u32..0xFD8F_u32,
    0xFD92_u32..0xFDC7_u32,
    0xFDCF_u32..0xFDCF_u32,
    0xFDF0_u32..0xFDFF_u32,
    0xFE70_u32..0xFE74_u32,
    0xFE76_u32..0xFEFC_u32,
    0x10E60_u32..0x10E7E_u32,
    0x10EC2_u32..0x10EC4_u32,
    0x10EFC_u32..0x10EFF_u32,
    0x1EE00_u32..0x1EE03_u32,
    0x1EE05_u32..0x1EE1F_u32,
    0x1EE21_u32..0x1EE22_u32,
    0x1EE24_u32..0x1EE24_u32,
    0x1EE27_u32..0x1EE27_u32,
    0x1EE29_u32..0x1EE32_u32,
    0x1EE34_u32..0x1EE37_u32,
    0x1EE39_u32..0x1EE39_u32,
    0x1EE3B_u32..0x1EE3B_u32,
    0x1EE42_u32..0x1EE42_u32,
    0x1EE47_u32..0x1EE47_u32,
    0x1EE49_u32..0x1EE49_u32,
    0x1EE4B_u32..0x1EE4B_u32,
    0x1EE4D_u32..0x1EE4F_u32,
    0x1EE51_u32..0x1EE52_u32,
    0x1EE54_u32..0x1EE54_u32,
    0x1EE57_u32..0x1EE57_u32,
    0x1EE59_u32..0x1EE59_u32,
    0x1EE5B_u32..0x1EE5B_u32,
    0x1EE5D_u32..0x1EE5D_u32,
    0x1EE5F_u32..0x1EE5F_u32,
    0x1EE61_u32..0x1EE62_u32,
    0x1EE64_u32..0x1EE64_u32,
    0x1EE67_u32..0x1EE6A_u32,
    0x1EE6C_u32..0x1EE72_u32,
    0x1EE74_u32..0x1EE77_u32,
    0x1EE79_u32..0x1EE7C_u32,
    0x1EE7E_u32..0x1EE7E_u32,
    0x1EE80_u32..0x1EE89_u32,
    0x1EE8B_u32..0x1EE9B_u32,
    0x1EEA1_u32..0x1EEA3_u32,
    0x1EEA5_u32..0x1EEA9_u32,
    0x1EEAB_u32..0x1EEBB_u32,
    0x1EEF0_u32..0x1EEF1_u32,
  ]

  # ARMENIAN
  ARMENIAN = [
    0x531_u32..0x556_u32,
    0x559_u32..0x58A_u32,
    0x58D_u32..0x58F_u32,
    0xFB13_u32..0xFB17_u32,
  ]

  # AVESTAN
  AVESTAN = [
    0x10B00_u32..0x10B35_u32,
    0x10B39_u32..0x10B3F_u32,
  ]

  # BALINESE
  BALINESE = [
    0x1B00_u32..0x1B4C_u32,
    0x1B4E_u32..0x1B7F_u32,
  ]

  # BAMUM
  BAMUM = [
    0xA6A0_u32..0xA6F7_u32,
    0x16800_u32..0x16A38_u32,
  ]

  # BASSA VAH
  BASSA_VAH = [
    0x16AD0_u32..0x16AED_u32,
    0x16AF0_u32..0x16AF5_u32,
  ]

  # BATAK
  BATAK = [
    0x1BC0_u32..0x1BF3_u32,
    0x1BFC_u32..0x1BFF_u32,
  ]

  # BENGALI
  BENGALI = [
    0x980_u32..0x983_u32,
    0x985_u32..0x98C_u32,
    0x98F_u32..0x990_u32,
    0x993_u32..0x9A8_u32,
    0x9AA_u32..0x9B0_u32,
    0x9B2_u32..0x9B2_u32,
    0x9B6_u32..0x9B9_u32,
    0x9BC_u32..0x9C4_u32,
    0x9C7_u32..0x9C8_u32,
    0x9CB_u32..0x9CE_u32,
    0x9D7_u32..0x9D7_u32,
    0x9DC_u32..0x9DD_u32,
    0x9DF_u32..0x9E3_u32,
    0x9E6_u32..0x9FE_u32,
  ]

  # BHAIKSUKI
  BHAIKSUKI = [
    0x11C00_u32..0x11C08_u32,
    0x11C0A_u32..0x11C36_u32,
    0x11C38_u32..0x11C45_u32,
    0x11C50_u32..0x11C6C_u32,
  ]

  # BOPOMOFO
  BOPOMOFO = [
    0x2EA_u32..0x2EB_u32,
    0x3105_u32..0x312F_u32,
    0x31A0_u32..0x31BF_u32,
  ]

  # BRAHMI
  BRAHMI = [
    0x11000_u32..0x1104D_u32,
    0x11052_u32..0x11075_u32,
    0x1107F_u32..0x1107F_u32,
  ]

  # BRAILLE
  BRAILLE = [
    0x2800_u32..0x28FF_u32,
  ]

  # BUGINESE
  BUGINESE = [
    0x1A00_u32..0x1A1B_u32,
    0x1A1E_u32..0x1A1F_u32,
  ]

  # BUHID
  BUHID = [
    0x1740_u32..0x1753_u32,
  ]

  # CANADIAN ABORIGINAL
  CANADIAN_ABORIGINAL = [
    0x1400_u32..0x167F_u32,
    0x18B0_u32..0x18F5_u32,
    0x11AB0_u32..0x11ABF_u32,
  ]

  # CARIAN
  CARIAN = [
    0x102A0_u32..0x102D0_u32,
  ]

  # CAUCASIAN ALBANIAN
  CAUCASIAN_ALBANIAN = [
    0x10530_u32..0x10563_u32,
    0x1056F_u32..0x1056F_u32,
  ]

  # CHAKMA
  CHAKMA = [
    0x11100_u32..0x11134_u32,
    0x11136_u32..0x11147_u32,
  ]

  # CHAM
  CHAM = [
    0xAA00_u32..0xAA36_u32,
    0xAA40_u32..0xAA4D_u32,
    0xAA50_u32..0xAA59_u32,
    0xAA5C_u32..0xAA5F_u32,
  ]

  # CHEROKEE
  CHEROKEE = [
    0x13A0_u32..0x13F5_u32,
    0x13F8_u32..0x13FD_u32,
    0xAB70_u32..0xABBF_u32,
  ]

  # CHORASMIAN
  CHORASMIAN = [
    0x10FB0_u32..0x10FCB_u32,
  ]

  # COMMON
  COMMON = [
    0x0_u32..0x40_u32,
    0x5B_u32..0x60_u32,
    0x7B_u32..0xA9_u32,
    0xAB_u32..0xB9_u32,
    0xBB_u32..0xBF_u32,
    0xD7_u32..0xD7_u32,
    0xF7_u32..0xF7_u32,
    0x2B9_u32..0x2DF_u32,
    0x2E5_u32..0x2E9_u32,
    0x2EC_u32..0x2FF_u32,
    0x374_u32..0x374_u32,
    0x37E_u32..0x37E_u32,
    0x385_u32..0x385_u32,
    0x387_u32..0x387_u32,
    0x605_u32..0x605_u32,
    0x60C_u32..0x60C_u32,
    0x61B_u32..0x61B_u32,
    0x61F_u32..0x61F_u32,
    0x640_u32..0x640_u32,
    0x6DD_u32..0x6DD_u32,
    0x8E2_u32..0x8E2_u32,
    0x964_u32..0x965_u32,
    0xE3F_u32..0xE3F_u32,
    0xFD5_u32..0xFD8_u32,
    0x10FB_u32..0x10FB_u32,
    0x16EB_u32..0x16ED_u32,
    0x1735_u32..0x1736_u32,
    0x1802_u32..0x1803_u32,
    0x1805_u32..0x1805_u32,
    0x1CD3_u32..0x1CD3_u32,
    0x1CE1_u32..0x1CE1_u32,
    0x1CE9_u32..0x1CEC_u32,
    0x1CEE_u32..0x1CF3_u32,
    0x1CF5_u32..0x1CF7_u32,
    0x1CFA_u32..0x1CFA_u32,
    0x2000_u32..0x200B_u32,
    0x200E_u32..0x2064_u32,
    0x2066_u32..0x2070_u32,
    0x2074_u32..0x207E_u32,
    0x2080_u32..0x208E_u32,
    0x20A0_u32..0x20C0_u32,
    0x2100_u32..0x2125_u32,
    0x2127_u32..0x2129_u32,
    0x212C_u32..0x2131_u32,
    0x2133_u32..0x214D_u32,
    0x214F_u32..0x215F_u32,
    0x2189_u32..0x218B_u32,
    0x2190_u32..0x2429_u32,
    0x2440_u32..0x244A_u32,
    0x2460_u32..0x27FF_u32,
    0x2900_u32..0x2B73_u32,
    0x2B76_u32..0x2B95_u32,
    0x2B97_u32..0x2BFF_u32,
    0x2E00_u32..0x2E5D_u32,
    0x2FF0_u32..0x3004_u32,
    0x3006_u32..0x3006_u32,
    0x3008_u32..0x3020_u32,
    0x3030_u32..0x3037_u32,
    0x303C_u32..0x303F_u32,
    0x309B_u32..0x309C_u32,
    0x30A0_u32..0x30A0_u32,
    0x30FB_u32..0x30FC_u32,
    0x3190_u32..0x319F_u32,
    0x31C0_u32..0x31E5_u32,
    0x31EF_u32..0x31EF_u32,
    0x3220_u32..0x325F_u32,
    0x327F_u32..0x32CF_u32,
    0x32FF_u32..0x32FF_u32,
    0x3358_u32..0x33FF_u32,
    0x4DC0_u32..0x4DFF_u32,
    0xA700_u32..0xA721_u32,
    0xA788_u32..0xA78A_u32,
    0xA830_u32..0xA839_u32,
    0xA92E_u32..0xA92E_u32,
    0xA9CF_u32..0xA9CF_u32,
    0xAB5B_u32..0xAB5B_u32,
    0xAB6A_u32..0xAB6B_u32,
    0xFD3E_u32..0xFD3F_u32,
    0xFE10_u32..0xFE19_u32,
    0xFE30_u32..0xFE52_u32,
    0xFE54_u32..0xFE66_u32,
    0xFE68_u32..0xFE6B_u32,
    0xFEFF_u32..0xFEFF_u32,
    0xFF01_u32..0xFF20_u32,
    0xFF3B_u32..0xFF40_u32,
    0xFF5B_u32..0xFF65_u32,
    0xFF70_u32..0xFF70_u32,
    0xFF9E_u32..0xFF9F_u32,
    0xFFE0_u32..0xFFE6_u32,
    0xFFE8_u32..0xFFEE_u32,
    0xFFF9_u32..0xFFFD_u32,
    0x10100_u32..0x10102_u32,
    0x10107_u32..0x10133_u32,
    0x10137_u32..0x1013F_u32,
    0x10190_u32..0x1019C_u32,
    0x101D0_u32..0x101FC_u32,
    0x102E1_u32..0x102FB_u32,
    0x1BCA0_u32..0x1BCA3_u32,
    0x1CC00_u32..0x1CCF9_u32,
    0x1CD00_u32..0x1CEB3_u32,
    0x1CF50_u32..0x1CFC3_u32,
    0x1D000_u32..0x1D0F5_u32,
    0x1D100_u32..0x1D126_u32,
    0x1D129_u32..0x1D166_u32,
    0x1D16A_u32..0x1D17A_u32,
    0x1D183_u32..0x1D184_u32,
    0x1D18C_u32..0x1D1A9_u32,
    0x1D1AE_u32..0x1D1EA_u32,
    0x1D2C0_u32..0x1D2D3_u32,
    0x1D2E0_u32..0x1D2F3_u32,
    0x1D300_u32..0x1D356_u32,
    0x1D360_u32..0x1D378_u32,
    0x1D400_u32..0x1D454_u32,
    0x1D456_u32..0x1D49C_u32,
    0x1D49E_u32..0x1D49F_u32,
    0x1D4A2_u32..0x1D4A2_u32,
    0x1D4A5_u32..0x1D4A6_u32,
    0x1D4A9_u32..0x1D4AC_u32,
    0x1D4AE_u32..0x1D4B9_u32,
    0x1D4BB_u32..0x1D4BB_u32,
    0x1D4BD_u32..0x1D4C3_u32,
    0x1D4C5_u32..0x1D505_u32,
    0x1D507_u32..0x1D50A_u32,
    0x1D50D_u32..0x1D514_u32,
    0x1D516_u32..0x1D51C_u32,
    0x1D51E_u32..0x1D539_u32,
    0x1D53B_u32..0x1D53E_u32,
    0x1D540_u32..0x1D544_u32,
    0x1D546_u32..0x1D546_u32,
    0x1D54A_u32..0x1D550_u32,
    0x1D552_u32..0x1D6A5_u32,
    0x1D6A8_u32..0x1D7CB_u32,
    0x1D7CE_u32..0x1D7FF_u32,
    0x1EC71_u32..0x1ECB4_u32,
    0x1ED01_u32..0x1ED3D_u32,
    0x1F000_u32..0x1F02B_u32,
    0x1F030_u32..0x1F093_u32,
    0x1F0A0_u32..0x1F0AE_u32,
    0x1F0B1_u32..0x1F0BF_u32,
    0x1F0C1_u32..0x1F0CF_u32,
    0x1F0D1_u32..0x1F0F5_u32,
    0x1F100_u32..0x1F1AD_u32,
    0x1F1E6_u32..0x1F1FF_u32,
    0x1F201_u32..0x1F202_u32,
    0x1F210_u32..0x1F23B_u32,
    0x1F240_u32..0x1F248_u32,
    0x1F250_u32..0x1F251_u32,
    0x1F260_u32..0x1F265_u32,
    0x1F300_u32..0x1F6D7_u32,
    0x1F6DC_u32..0x1F6EC_u32,
    0x1F6F0_u32..0x1F6FC_u32,
    0x1F700_u32..0x1F776_u32,
    0x1F77B_u32..0x1F7D9_u32,
    0x1F7E0_u32..0x1F7EB_u32,
    0x1F7F0_u32..0x1F7F0_u32,
    0x1F800_u32..0x1F80B_u32,
    0x1F810_u32..0x1F847_u32,
    0x1F850_u32..0x1F859_u32,
    0x1F860_u32..0x1F887_u32,
    0x1F890_u32..0x1F8AD_u32,
    0x1F8B0_u32..0x1F8BB_u32,
    0x1F8C0_u32..0x1F8C1_u32,
    0x1F900_u32..0x1FA53_u32,
    0x1FA60_u32..0x1FA6D_u32,
    0x1FA70_u32..0x1FA7C_u32,
    0x1FA80_u32..0x1FA89_u32,
    0x1FA8F_u32..0x1FAC6_u32,
    0x1FACE_u32..0x1FADC_u32,
    0x1FADF_u32..0x1FAE9_u32,
    0x1FAF0_u32..0x1FAF8_u32,
    0x1FB00_u32..0x1FB92_u32,
    0x1FB94_u32..0x1FBF9_u32,
    0xE0001_u32..0xE0001_u32,
    0xE0020_u32..0xE007F_u32,
  ]

  # COPTIC
  COPTIC = [
    0x3E2_u32..0x3EF_u32,
    0x2C80_u32..0x2CF3_u32,
    0x2CF9_u32..0x2CFF_u32,
  ]

  # CUNEIFORM
  CUNEIFORM = [
    0x12000_u32..0x12399_u32,
    0x12400_u32..0x1246E_u32,
    0x12470_u32..0x12474_u32,
    0x12480_u32..0x12543_u32,
  ]

  # CYPRIOT
  CYPRIOT = [
    0x10800_u32..0x10805_u32,
    0x10808_u32..0x10808_u32,
    0x1080A_u32..0x10835_u32,
    0x10837_u32..0x10838_u32,
    0x1083C_u32..0x1083C_u32,
    0x1083F_u32..0x1083F_u32,
  ]

  # CYPRO MINOAN
  CYPRO_MINOAN = [
    0x12F90_u32..0x12FF2_u32,
  ]

  # CYRILLIC
  CYRILLIC = [
    0x400_u32..0x484_u32,
    0x487_u32..0x52F_u32,
    0x1C80_u32..0x1C8A_u32,
    0x1D2B_u32..0x1D2B_u32,
    0x1D78_u32..0x1D78_u32,
    0x2DE0_u32..0x2DFF_u32,
    0xA640_u32..0xA69F_u32,
    0xFE2E_u32..0xFE2F_u32,
    0x1E030_u32..0x1E06D_u32,
    0x1E08F_u32..0x1E08F_u32,
  ]

  # DESERET
  DESERET = [
    0x10400_u32..0x1044F_u32,
  ]

  # DEVANAGARI
  DEVANAGARI = [
    0x900_u32..0x950_u32,
    0x955_u32..0x963_u32,
    0x966_u32..0x97F_u32,
    0xA8E0_u32..0xA8FF_u32,
    0x11B00_u32..0x11B09_u32,
  ]

  # DIVES AKURU
  DIVES_AKURU = [
    0x11900_u32..0x11906_u32,
    0x11909_u32..0x11909_u32,
    0x1190C_u32..0x11913_u32,
    0x11915_u32..0x11916_u32,
    0x11918_u32..0x11935_u32,
    0x11937_u32..0x11938_u32,
    0x1193B_u32..0x11946_u32,
    0x11950_u32..0x11959_u32,
  ]

  # DOGRA
  DOGRA = [
    0x11800_u32..0x1183B_u32,
  ]

  # DUPLOYAN
  DUPLOYAN = [
    0x1BC00_u32..0x1BC6A_u32,
    0x1BC70_u32..0x1BC7C_u32,
    0x1BC80_u32..0x1BC88_u32,
    0x1BC90_u32..0x1BC99_u32,
    0x1BC9C_u32..0x1BC9F_u32,
  ]

  # EGYPTIAN HIEROGLYPHS
  EGYPTIAN_HIEROGLYPHS = [
    0x13000_u32..0x13455_u32,
    0x13460_u32..0x143FA_u32,
  ]

  # ELBASAN
  ELBASAN = [
    0x10500_u32..0x10527_u32,
  ]

  # ELYMAIC
  ELYMAIC = [
    0x10FE0_u32..0x10FF6_u32,
  ]

  # ETHIOPIC
  ETHIOPIC = [
    0x1200_u32..0x1248_u32,
    0x124A_u32..0x124D_u32,
    0x1250_u32..0x1256_u32,
    0x1258_u32..0x1258_u32,
    0x125A_u32..0x125D_u32,
    0x1260_u32..0x1288_u32,
    0x128A_u32..0x128D_u32,
    0x1290_u32..0x12B0_u32,
    0x12B2_u32..0x12B5_u32,
    0x12B8_u32..0x12BE_u32,
    0x12C0_u32..0x12C0_u32,
    0x12C2_u32..0x12C5_u32,
    0x12C8_u32..0x12D6_u32,
    0x12D8_u32..0x1310_u32,
    0x1312_u32..0x1315_u32,
    0x1318_u32..0x135A_u32,
    0x135D_u32..0x137C_u32,
    0x1380_u32..0x1399_u32,
    0x2D80_u32..0x2D96_u32,
    0x2DA0_u32..0x2DA6_u32,
    0x2DA8_u32..0x2DAE_u32,
    0x2DB0_u32..0x2DB6_u32,
    0x2DB8_u32..0x2DBE_u32,
    0x2DC0_u32..0x2DC6_u32,
    0x2DC8_u32..0x2DCE_u32,
    0x2DD0_u32..0x2DD6_u32,
    0x2DD8_u32..0x2DDE_u32,
    0xAB01_u32..0xAB06_u32,
    0xAB09_u32..0xAB0E_u32,
    0xAB11_u32..0xAB16_u32,
    0xAB20_u32..0xAB26_u32,
    0xAB28_u32..0xAB2E_u32,
    0x1E7E0_u32..0x1E7E6_u32,
    0x1E7E8_u32..0x1E7EB_u32,
    0x1E7ED_u32..0x1E7EE_u32,
    0x1E7F0_u32..0x1E7FE_u32,
  ]

  # GARAY
  GARAY = [
    0x10D40_u32..0x10D65_u32,
    0x10D69_u32..0x10D85_u32,
    0x10D8E_u32..0x10D8F_u32,
  ]

  # GEORGIAN
  GEORGIAN = [
    0x10A0_u32..0x10C5_u32,
    0x10C7_u32..0x10C7_u32,
    0x10CD_u32..0x10CD_u32,
    0x10D0_u32..0x10FA_u32,
    0x10FC_u32..0x10FF_u32,
    0x1C90_u32..0x1CBA_u32,
    0x1CBD_u32..0x1CBF_u32,
    0x2D00_u32..0x2D25_u32,
    0x2D27_u32..0x2D27_u32,
    0x2D2D_u32..0x2D2D_u32,
  ]

  # GLAGOLITIC
  GLAGOLITIC = [
    0x2C00_u32..0x2C5F_u32,
    0x1E000_u32..0x1E006_u32,
    0x1E008_u32..0x1E018_u32,
    0x1E01B_u32..0x1E021_u32,
    0x1E023_u32..0x1E024_u32,
    0x1E026_u32..0x1E02A_u32,
  ]

  # GOTHIC
  GOTHIC = [
    0x10330_u32..0x1034A_u32,
  ]

  # GRANTHA
  GRANTHA = [
    0x11300_u32..0x11303_u32,
    0x11305_u32..0x1130C_u32,
    0x1130F_u32..0x11310_u32,
    0x11313_u32..0x11328_u32,
    0x1132A_u32..0x11330_u32,
    0x11332_u32..0x11333_u32,
    0x11335_u32..0x11339_u32,
    0x1133C_u32..0x11344_u32,
    0x11347_u32..0x11348_u32,
    0x1134B_u32..0x1134D_u32,
    0x11350_u32..0x11350_u32,
    0x11357_u32..0x11357_u32,
    0x1135D_u32..0x11363_u32,
    0x11366_u32..0x1136C_u32,
    0x11370_u32..0x11374_u32,
  ]

  # GREEK
  GREEK = [
    0x370_u32..0x373_u32,
    0x375_u32..0x377_u32,
    0x37A_u32..0x37D_u32,
    0x37F_u32..0x37F_u32,
    0x384_u32..0x384_u32,
    0x386_u32..0x386_u32,
    0x388_u32..0x38A_u32,
    0x38C_u32..0x38C_u32,
    0x38E_u32..0x3A1_u32,
    0x3A3_u32..0x3E1_u32,
    0x3F0_u32..0x3FF_u32,
    0x1D26_u32..0x1D2A_u32,
    0x1D5D_u32..0x1D61_u32,
    0x1D66_u32..0x1D6A_u32,
    0x1DBF_u32..0x1DBF_u32,
    0x1F00_u32..0x1F15_u32,
    0x1F18_u32..0x1F1D_u32,
    0x1F20_u32..0x1F45_u32,
    0x1F48_u32..0x1F4D_u32,
    0x1F50_u32..0x1F57_u32,
    0x1F59_u32..0x1F59_u32,
    0x1F5B_u32..0x1F5B_u32,
    0x1F5D_u32..0x1F5D_u32,
    0x1F5F_u32..0x1F7D_u32,
    0x1F80_u32..0x1FB4_u32,
    0x1FB6_u32..0x1FC4_u32,
    0x1FC6_u32..0x1FD3_u32,
    0x1FD6_u32..0x1FDB_u32,
    0x1FDD_u32..0x1FEF_u32,
    0x1FF2_u32..0x1FF4_u32,
    0x1FF6_u32..0x1FFE_u32,
    0x2126_u32..0x2126_u32,
    0xAB65_u32..0xAB65_u32,
    0x10140_u32..0x1018E_u32,
    0x101A0_u32..0x101A0_u32,
    0x1D200_u32..0x1D245_u32,
  ]

  # GUJARATI
  GUJARATI = [
    0xA81_u32..0xA83_u32,
    0xA85_u32..0xA8D_u32,
    0xA8F_u32..0xA91_u32,
    0xA93_u32..0xAA8_u32,
    0xAAA_u32..0xAB0_u32,
    0xAB2_u32..0xAB3_u32,
    0xAB5_u32..0xAB9_u32,
    0xABC_u32..0xAC5_u32,
    0xAC7_u32..0xAC9_u32,
    0xACB_u32..0xACD_u32,
    0xAD0_u32..0xAD0_u32,
    0xAE0_u32..0xAE3_u32,
    0xAE6_u32..0xAF1_u32,
    0xAF9_u32..0xAFF_u32,
  ]

  # GUNJALA GONDI
  GUNJALA_GONDI = [
    0x11D60_u32..0x11D65_u32,
    0x11D67_u32..0x11D68_u32,
    0x11D6A_u32..0x11D8E_u32,
    0x11D90_u32..0x11D91_u32,
    0x11D93_u32..0x11D98_u32,
    0x11DA0_u32..0x11DA9_u32,
  ]

  # GURMUKHI
  GURMUKHI = [
    0xA01_u32..0xA03_u32,
    0xA05_u32..0xA0A_u32,
    0xA0F_u32..0xA10_u32,
    0xA13_u32..0xA28_u32,
    0xA2A_u32..0xA30_u32,
    0xA32_u32..0xA33_u32,
    0xA35_u32..0xA36_u32,
    0xA38_u32..0xA39_u32,
    0xA3C_u32..0xA3C_u32,
    0xA3E_u32..0xA42_u32,
    0xA47_u32..0xA48_u32,
    0xA4B_u32..0xA4D_u32,
    0xA51_u32..0xA51_u32,
    0xA59_u32..0xA5C_u32,
    0xA5E_u32..0xA5E_u32,
    0xA66_u32..0xA76_u32,
  ]

  # GURUNG KHEMA
  GURUNG_KHEMA = [
    0x16100_u32..0x16139_u32,
  ]

  # HAN
  HAN = [
    0x2E80_u32..0x2E99_u32,
    0x2E9B_u32..0x2EF3_u32,
    0x2F00_u32..0x2FD5_u32,
    0x3005_u32..0x3005_u32,
    0x3007_u32..0x3007_u32,
    0x3021_u32..0x3029_u32,
    0x3038_u32..0x303B_u32,
    0x3400_u32..0x4DBF_u32,
    0x4E00_u32..0x9FFF_u32,
    0xF900_u32..0xFA6D_u32,
    0xFA70_u32..0xFAD9_u32,
    0x16FE2_u32..0x16FE3_u32,
    0x16FF0_u32..0x16FF1_u32,
    0x20000_u32..0x2A6DF_u32,
    0x2A700_u32..0x2B739_u32,
    0x2B740_u32..0x2B81D_u32,
    0x2B820_u32..0x2CEA1_u32,
    0x2CEB0_u32..0x2EBE0_u32,
    0x2EBF0_u32..0x2EE5D_u32,
    0x2F800_u32..0x2FA1D_u32,
    0x30000_u32..0x3134A_u32,
    0x31350_u32..0x323AF_u32,
  ]

  # HANGUL
  HANGUL = [
    0x1100_u32..0x11FF_u32,
    0x302E_u32..0x302F_u32,
    0x3131_u32..0x318E_u32,
    0x3200_u32..0x321E_u32,
    0x3260_u32..0x327E_u32,
    0xA960_u32..0xA97C_u32,
    0xAC00_u32..0xD7A3_u32,
    0xD7B0_u32..0xD7C6_u32,
    0xD7CB_u32..0xD7FB_u32,
    0xFFA0_u32..0xFFBE_u32,
    0xFFC2_u32..0xFFC7_u32,
    0xFFCA_u32..0xFFCF_u32,
    0xFFD2_u32..0xFFD7_u32,
    0xFFDA_u32..0xFFDC_u32,
  ]

  # HANIFI ROHINGYA
  HANIFI_ROHINGYA = [
    0x10D00_u32..0x10D27_u32,
    0x10D30_u32..0x10D39_u32,
  ]

  # HANUNOO
  HANUNOO = [
    0x1720_u32..0x1734_u32,
  ]

  # HATRAN
  HATRAN = [
    0x108E0_u32..0x108F2_u32,
    0x108F4_u32..0x108F5_u32,
    0x108FB_u32..0x108FF_u32,
  ]

  # HEBREW
  HEBREW = [
    0x591_u32..0x5C7_u32,
    0x5D0_u32..0x5EA_u32,
    0x5EF_u32..0x5F4_u32,
    0xFB1D_u32..0xFB36_u32,
    0xFB38_u32..0xFB3C_u32,
    0xFB3E_u32..0xFB3E_u32,
    0xFB40_u32..0xFB41_u32,
    0xFB43_u32..0xFB44_u32,
    0xFB46_u32..0xFB4F_u32,
  ]

  # HIRAGANA
  HIRAGANA = [
    0x3041_u32..0x3096_u32,
    0x309D_u32..0x309F_u32,
    0x1B001_u32..0x1B11F_u32,
    0x1B132_u32..0x1B132_u32,
    0x1B150_u32..0x1B152_u32,
    0x1F200_u32..0x1F200_u32,
  ]

  # IMPERIAL ARAMAIC
  IMPERIAL_ARAMAIC = [
    0x10840_u32..0x10855_u32,
    0x10857_u32..0x1085F_u32,
  ]

  # INHERITED
  INHERITED = [
    0x300_u32..0x36F_u32,
    0x485_u32..0x486_u32,
    0x64B_u32..0x655_u32,
    0x670_u32..0x670_u32,
    0x951_u32..0x954_u32,
    0x1AB0_u32..0x1ACE_u32,
    0x1CD0_u32..0x1CD2_u32,
    0x1CD4_u32..0x1CE0_u32,
    0x1CE2_u32..0x1CE8_u32,
    0x1CED_u32..0x1CED_u32,
    0x1CF4_u32..0x1CF4_u32,
    0x1CF8_u32..0x1CF9_u32,
    0x1DC0_u32..0x1DFF_u32,
    0x200C_u32..0x200D_u32,
    0x20D0_u32..0x20F0_u32,
    0x302A_u32..0x302D_u32,
    0x3099_u32..0x309A_u32,
    0xFE00_u32..0xFE0F_u32,
    0xFE20_u32..0xFE2D_u32,
    0x101FD_u32..0x101FD_u32,
    0x102E0_u32..0x102E0_u32,
    0x1133B_u32..0x1133B_u32,
    0x1CF00_u32..0x1CF2D_u32,
    0x1CF30_u32..0x1CF46_u32,
    0x1D167_u32..0x1D169_u32,
    0x1D17B_u32..0x1D182_u32,
    0x1D185_u32..0x1D18B_u32,
    0x1D1AA_u32..0x1D1AD_u32,
    0xE0100_u32..0xE01EF_u32,
  ]

  # INSCRIPTIONAL PAHLAVI
  INSCRIPTIONAL_PAHLAVI = [
    0x10B60_u32..0x10B72_u32,
    0x10B78_u32..0x10B7F_u32,
  ]

  # INSCRIPTIONAL PARTHIAN
  INSCRIPTIONAL_PARTHIAN = [
    0x10B40_u32..0x10B55_u32,
    0x10B58_u32..0x10B5F_u32,
  ]

  # JAVANESE
  JAVANESE = [
    0xA980_u32..0xA9CD_u32,
    0xA9D0_u32..0xA9D9_u32,
    0xA9DE_u32..0xA9DF_u32,
  ]

  # KAITHI
  KAITHI = [
    0x11080_u32..0x110C2_u32,
    0x110CD_u32..0x110CD_u32,
  ]

  # KANNADA
  KANNADA = [
    0xC80_u32..0xC8C_u32,
    0xC8E_u32..0xC90_u32,
    0xC92_u32..0xCA8_u32,
    0xCAA_u32..0xCB3_u32,
    0xCB5_u32..0xCB9_u32,
    0xCBC_u32..0xCC4_u32,
    0xCC6_u32..0xCC8_u32,
    0xCCA_u32..0xCCD_u32,
    0xCD5_u32..0xCD6_u32,
    0xCDD_u32..0xCDE_u32,
    0xCE0_u32..0xCE3_u32,
    0xCE6_u32..0xCEF_u32,
    0xCF1_u32..0xCF3_u32,
  ]

  # KATAKANA
  KATAKANA = [
    0x30A1_u32..0x30FA_u32,
    0x30FD_u32..0x30FF_u32,
    0x31F0_u32..0x31FF_u32,
    0x32D0_u32..0x32FE_u32,
    0x3300_u32..0x3357_u32,
    0xFF66_u32..0xFF6F_u32,
    0xFF71_u32..0xFF9D_u32,
    0x1AFF0_u32..0x1AFF3_u32,
    0x1AFF5_u32..0x1AFFB_u32,
    0x1AFFD_u32..0x1AFFE_u32,
    0x1B000_u32..0x1B000_u32,
    0x1B120_u32..0x1B122_u32,
    0x1B155_u32..0x1B155_u32,
    0x1B164_u32..0x1B167_u32,
  ]

  # KAWI
  KAWI = [
    0x11F00_u32..0x11F10_u32,
    0x11F12_u32..0x11F3A_u32,
    0x11F3E_u32..0x11F5A_u32,
  ]

  # KAYAH LI
  KAYAH_LI = [
    0xA900_u32..0xA92D_u32,
    0xA92F_u32..0xA92F_u32,
  ]

  # KHAROSHTHI
  KHAROSHTHI = [
    0x10A00_u32..0x10A03_u32,
    0x10A05_u32..0x10A06_u32,
    0x10A0C_u32..0x10A13_u32,
    0x10A15_u32..0x10A17_u32,
    0x10A19_u32..0x10A35_u32,
    0x10A38_u32..0x10A3A_u32,
    0x10A3F_u32..0x10A48_u32,
    0x10A50_u32..0x10A58_u32,
  ]

  # KHITAN SMALL SCRIPT
  KHITAN_SMALL_SCRIPT = [
    0x16FE4_u32..0x16FE4_u32,
    0x18B00_u32..0x18CD5_u32,
    0x18CFF_u32..0x18CFF_u32,
  ]

  # KHMER
  KHMER = [
    0x1780_u32..0x17DD_u32,
    0x17E0_u32..0x17E9_u32,
    0x17F0_u32..0x17F9_u32,
    0x19E0_u32..0x19FF_u32,
  ]

  # KHOJKI
  KHOJKI = [
    0x11200_u32..0x11211_u32,
    0x11213_u32..0x11241_u32,
  ]

  # KHUDAWADI
  KHUDAWADI = [
    0x112B0_u32..0x112EA_u32,
    0x112F0_u32..0x112F9_u32,
  ]

  # KIRAT RAI
  KIRAT_RAI = [
    0x16D40_u32..0x16D79_u32,
  ]

  # LAO
  LAO = [
    0xE81_u32..0xE82_u32,
    0xE84_u32..0xE84_u32,
    0xE86_u32..0xE8A_u32,
    0xE8C_u32..0xEA3_u32,
    0xEA5_u32..0xEA5_u32,
    0xEA7_u32..0xEBD_u32,
    0xEC0_u32..0xEC4_u32,
    0xEC6_u32..0xEC6_u32,
    0xEC8_u32..0xECE_u32,
    0xED0_u32..0xED9_u32,
    0xEDC_u32..0xEDF_u32,
  ]

  # LATIN
  LATIN = [
    0x41_u32..0x5A_u32,
    0x61_u32..0x7A_u32,
    0xAA_u32..0xAA_u32,
    0xBA_u32..0xBA_u32,
    0xC0_u32..0xD6_u32,
    0xD8_u32..0xF6_u32,
    0xF8_u32..0x2B8_u32,
    0x2E0_u32..0x2E4_u32,
    0x1D00_u32..0x1D25_u32,
    0x1D2C_u32..0x1D5C_u32,
    0x1D62_u32..0x1D65_u32,
    0x1D6B_u32..0x1D77_u32,
    0x1D79_u32..0x1DBE_u32,
    0x1E00_u32..0x1EFF_u32,
    0x2071_u32..0x2071_u32,
    0x207F_u32..0x207F_u32,
    0x2090_u32..0x209C_u32,
    0x212A_u32..0x212B_u32,
    0x2132_u32..0x2132_u32,
    0x214E_u32..0x214E_u32,
    0x2160_u32..0x2188_u32,
    0x2C60_u32..0x2C7F_u32,
    0xA722_u32..0xA787_u32,
    0xA78B_u32..0xA7CD_u32,
    0xA7D0_u32..0xA7D1_u32,
    0xA7D3_u32..0xA7D3_u32,
    0xA7D5_u32..0xA7DC_u32,
    0xA7F2_u32..0xA7FF_u32,
    0xAB30_u32..0xAB5A_u32,
    0xAB5C_u32..0xAB64_u32,
    0xAB66_u32..0xAB69_u32,
    0xFB00_u32..0xFB06_u32,
    0xFF21_u32..0xFF3A_u32,
    0xFF41_u32..0xFF5A_u32,
    0x10780_u32..0x10785_u32,
    0x10787_u32..0x107B0_u32,
    0x107B2_u32..0x107BA_u32,
    0x1DF00_u32..0x1DF1E_u32,
    0x1DF25_u32..0x1DF2A_u32,
  ]

  # LEPCHA
  LEPCHA = [
    0x1C00_u32..0x1C37_u32,
    0x1C3B_u32..0x1C49_u32,
    0x1C4D_u32..0x1C4F_u32,
  ]

  # LIMBU
  LIMBU = [
    0x1900_u32..0x191E_u32,
    0x1920_u32..0x192B_u32,
    0x1930_u32..0x193B_u32,
    0x1940_u32..0x1940_u32,
    0x1944_u32..0x194F_u32,
  ]

  # LINEAR A
  LINEAR_A = [
    0x10600_u32..0x10736_u32,
    0x10740_u32..0x10755_u32,
    0x10760_u32..0x10767_u32,
  ]

  # LINEAR B
  LINEAR_B = [
    0x10000_u32..0x1000B_u32,
    0x1000D_u32..0x10026_u32,
    0x10028_u32..0x1003A_u32,
    0x1003C_u32..0x1003D_u32,
    0x1003F_u32..0x1004D_u32,
    0x10050_u32..0x1005D_u32,
    0x10080_u32..0x100FA_u32,
  ]

  # LISU
  LISU = [
    0xA4D0_u32..0xA4FF_u32,
    0x11FB0_u32..0x11FB0_u32,
  ]

  # LYCIAN
  LYCIAN = [
    0x10280_u32..0x1029C_u32,
  ]

  # LYDIAN
  LYDIAN = [
    0x10920_u32..0x10939_u32,
    0x1093F_u32..0x1093F_u32,
  ]

  # MAHAJANI
  MAHAJANI = [
    0x11150_u32..0x11176_u32,
  ]

  # MAKASAR
  MAKASAR = [
    0x11EE0_u32..0x11EF8_u32,
  ]

  # MALAYALAM
  MALAYALAM = [
    0xD00_u32..0xD0C_u32,
    0xD0E_u32..0xD10_u32,
    0xD12_u32..0xD44_u32,
    0xD46_u32..0xD48_u32,
    0xD4A_u32..0xD4F_u32,
    0xD54_u32..0xD63_u32,
    0xD66_u32..0xD7F_u32,
  ]

  # MANDAIC
  MANDAIC = [
    0x840_u32..0x85B_u32,
    0x85E_u32..0x85E_u32,
  ]

  # MANICHAEAN
  MANICHAEAN = [
    0x10AC0_u32..0x10AE6_u32,
    0x10AEB_u32..0x10AF6_u32,
  ]

  # MARCHEN
  MARCHEN = [
    0x11C70_u32..0x11C8F_u32,
    0x11C92_u32..0x11CA7_u32,
    0x11CA9_u32..0x11CB6_u32,
  ]

  # MASARAM GONDI
  MASARAM_GONDI = [
    0x11D00_u32..0x11D06_u32,
    0x11D08_u32..0x11D09_u32,
    0x11D0B_u32..0x11D36_u32,
    0x11D3A_u32..0x11D3A_u32,
    0x11D3C_u32..0x11D3D_u32,
    0x11D3F_u32..0x11D47_u32,
    0x11D50_u32..0x11D59_u32,
  ]

  # MEDEFAIDRIN
  MEDEFAIDRIN = [
    0x16E40_u32..0x16E9A_u32,
  ]

  # MEETEI MAYEK
  MEETEI_MAYEK = [
    0xAAE0_u32..0xAAF6_u32,
    0xABC0_u32..0xABED_u32,
    0xABF0_u32..0xABF9_u32,
  ]

  # MENDE KIKAKUI
  MENDE_KIKAKUI = [
    0x1E800_u32..0x1E8C4_u32,
    0x1E8C7_u32..0x1E8D6_u32,
  ]

  # MEROITIC CURSIVE
  MEROITIC_CURSIVE = [
    0x109A0_u32..0x109B7_u32,
    0x109BC_u32..0x109CF_u32,
    0x109D2_u32..0x109FF_u32,
  ]

  # MEROITIC HIEROGLYPHS
  MEROITIC_HIEROGLYPHS = [
    0x10980_u32..0x1099F_u32,
  ]

  # MIAO
  MIAO = [
    0x16F00_u32..0x16F4A_u32,
    0x16F4F_u32..0x16F87_u32,
    0x16F8F_u32..0x16F9F_u32,
  ]

  # MODI
  MODI = [
    0x11600_u32..0x11644_u32,
    0x11650_u32..0x11659_u32,
  ]

  # MONGOLIAN
  MONGOLIAN = [
    0x1800_u32..0x1801_u32,
    0x1804_u32..0x1804_u32,
    0x1806_u32..0x1819_u32,
    0x1820_u32..0x1878_u32,
    0x1880_u32..0x18AA_u32,
    0x11660_u32..0x1166C_u32,
  ]

  # MRO
  MRO = [
    0x16A40_u32..0x16A5E_u32,
    0x16A60_u32..0x16A69_u32,
    0x16A6E_u32..0x16A6F_u32,
  ]

  # MULTANI
  MULTANI = [
    0x11280_u32..0x11286_u32,
    0x11288_u32..0x11288_u32,
    0x1128A_u32..0x1128D_u32,
    0x1128F_u32..0x1129D_u32,
    0x1129F_u32..0x112A9_u32,
  ]

  # MYANMAR
  MYANMAR = [
    0x1000_u32..0x109F_u32,
    0xA9E0_u32..0xA9FE_u32,
    0xAA60_u32..0xAA7F_u32,
    0x116D0_u32..0x116E3_u32,
  ]

  # NABATAEAN
  NABATAEAN = [
    0x10880_u32..0x1089E_u32,
    0x108A7_u32..0x108AF_u32,
  ]

  # NAG MUNDARI
  NAG_MUNDARI = [
    0x1E4D0_u32..0x1E4F9_u32,
  ]

  # NANDINAGARI
  NANDINAGARI = [
    0x119A0_u32..0x119A7_u32,
    0x119AA_u32..0x119D7_u32,
    0x119DA_u32..0x119E4_u32,
  ]

  # NEW TAI LUE
  NEW_TAI_LUE = [
    0x1980_u32..0x19AB_u32,
    0x19B0_u32..0x19C9_u32,
    0x19D0_u32..0x19DA_u32,
    0x19DE_u32..0x19DF_u32,
  ]

  # NEWA
  NEWA = [
    0x11400_u32..0x1145B_u32,
    0x1145D_u32..0x11461_u32,
  ]

  # NKO
  NKO = [
    0x7C0_u32..0x7FA_u32,
    0x7FD_u32..0x7FF_u32,
  ]

  # NUSHU
  NUSHU = [
    0x16FE1_u32..0x16FE1_u32,
    0x1B170_u32..0x1B2FB_u32,
  ]

  # NYIAKENG PUACHUE HMONG
  NYIAKENG_PUACHUE_HMONG = [
    0x1E100_u32..0x1E12C_u32,
    0x1E130_u32..0x1E13D_u32,
    0x1E140_u32..0x1E149_u32,
    0x1E14E_u32..0x1E14F_u32,
  ]

  # OGHAM
  OGHAM = [
    0x1680_u32..0x169C_u32,
  ]

  # OL CHIKI
  OL_CHIKI = [
    0x1C50_u32..0x1C7F_u32,
  ]

  # OL ONAL
  OL_ONAL = [
    0x1E5D0_u32..0x1E5FA_u32,
    0x1E5FF_u32..0x1E5FF_u32,
  ]

  # OLD HUNGARIAN
  OLD_HUNGARIAN = [
    0x10C80_u32..0x10CB2_u32,
    0x10CC0_u32..0x10CF2_u32,
    0x10CFA_u32..0x10CFF_u32,
  ]

  # OLD ITALIC
  OLD_ITALIC = [
    0x10300_u32..0x10323_u32,
    0x1032D_u32..0x1032F_u32,
  ]

  # OLD NORTH ARABIAN
  OLD_NORTH_ARABIAN = [
    0x10A80_u32..0x10A9F_u32,
  ]

  # OLD PERMIC
  OLD_PERMIC = [
    0x10350_u32..0x1037A_u32,
  ]

  # OLD PERSIAN
  OLD_PERSIAN = [
    0x103A0_u32..0x103C3_u32,
    0x103C8_u32..0x103D5_u32,
  ]

  # OLD SOGDIAN
  OLD_SOGDIAN = [
    0x10F00_u32..0x10F27_u32,
  ]

  # OLD SOUTH ARABIAN
  OLD_SOUTH_ARABIAN = [
    0x10A60_u32..0x10A7F_u32,
  ]

  # OLD TURKIC
  OLD_TURKIC = [
    0x10C00_u32..0x10C48_u32,
  ]

  # OLD UYGHUR
  OLD_UYGHUR = [
    0x10F70_u32..0x10F89_u32,
  ]

  # ORIYA
  ORIYA = [
    0xB01_u32..0xB03_u32,
    0xB05_u32..0xB0C_u32,
    0xB0F_u32..0xB10_u32,
    0xB13_u32..0xB28_u32,
    0xB2A_u32..0xB30_u32,
    0xB32_u32..0xB33_u32,
    0xB35_u32..0xB39_u32,
    0xB3C_u32..0xB44_u32,
    0xB47_u32..0xB48_u32,
    0xB4B_u32..0xB4D_u32,
    0xB55_u32..0xB57_u32,
    0xB5C_u32..0xB5D_u32,
    0xB5F_u32..0xB63_u32,
    0xB66_u32..0xB77_u32,
  ]

  # OSAGE
  OSAGE = [
    0x104B0_u32..0x104D3_u32,
    0x104D8_u32..0x104FB_u32,
  ]

  # OSMANYA
  OSMANYA = [
    0x10480_u32..0x1049D_u32,
    0x104A0_u32..0x104A9_u32,
  ]

  # PAHAWH HMONG
  PAHAWH_HMONG = [
    0x16B00_u32..0x16B45_u32,
    0x16B50_u32..0x16B59_u32,
    0x16B5B_u32..0x16B61_u32,
    0x16B63_u32..0x16B77_u32,
    0x16B7D_u32..0x16B8F_u32,
  ]

  # PALMYRENE
  PALMYRENE = [
    0x10860_u32..0x1087F_u32,
  ]

  # PAU CIN HAU
  PAU_CIN_HAU = [
    0x11AC0_u32..0x11AF8_u32,
  ]

  # PHAGS PA
  PHAGS_PA = [
    0xA840_u32..0xA877_u32,
  ]

  # PHOENICIAN
  PHOENICIAN = [
    0x10900_u32..0x1091B_u32,
    0x1091F_u32..0x1091F_u32,
  ]

  # PSALTER PAHLAVI
  PSALTER_PAHLAVI = [
    0x10B80_u32..0x10B91_u32,
    0x10B99_u32..0x10B9C_u32,
    0x10BA9_u32..0x10BAF_u32,
  ]

  # REJANG
  REJANG = [
    0xA930_u32..0xA953_u32,
    0xA95F_u32..0xA95F_u32,
  ]

  # RUNIC
  RUNIC = [
    0x16A0_u32..0x16EA_u32,
    0x16EE_u32..0x16F8_u32,
  ]

  # SAMARITAN
  SAMARITAN = [
    0x800_u32..0x82D_u32,
    0x830_u32..0x83E_u32,
  ]

  # SAURASHTRA
  SAURASHTRA = [
    0xA880_u32..0xA8C5_u32,
    0xA8CE_u32..0xA8D9_u32,
  ]

  # SHARADA
  SHARADA = [
    0x11180_u32..0x111DF_u32,
  ]

  # SHAVIAN
  SHAVIAN = [
    0x10450_u32..0x1047F_u32,
  ]

  # SIDDHAM
  SIDDHAM = [
    0x11580_u32..0x115B5_u32,
    0x115B8_u32..0x115DD_u32,
  ]

  # SIGNWRITING
  SIGNWRITING = [
    0x1D800_u32..0x1DA8B_u32,
    0x1DA9B_u32..0x1DA9F_u32,
    0x1DAA1_u32..0x1DAAF_u32,
  ]

  # SINHALA
  SINHALA = [
    0xD81_u32..0xD83_u32,
    0xD85_u32..0xD96_u32,
    0xD9A_u32..0xDB1_u32,
    0xDB3_u32..0xDBB_u32,
    0xDBD_u32..0xDBD_u32,
    0xDC0_u32..0xDC6_u32,
    0xDCA_u32..0xDCA_u32,
    0xDCF_u32..0xDD4_u32,
    0xDD6_u32..0xDD6_u32,
    0xDD8_u32..0xDDF_u32,
    0xDE6_u32..0xDEF_u32,
    0xDF2_u32..0xDF4_u32,
    0x111E1_u32..0x111F4_u32,
  ]

  # SOGDIAN
  SOGDIAN = [
    0x10F30_u32..0x10F59_u32,
  ]

  # SORA SOMPENG
  SORA_SOMPENG = [
    0x110D0_u32..0x110E8_u32,
    0x110F0_u32..0x110F9_u32,
  ]

  # SOYOMBO
  SOYOMBO = [
    0x11A50_u32..0x11AA2_u32,
  ]

  # SUNDANESE
  SUNDANESE = [
    0x1B80_u32..0x1BBF_u32,
    0x1CC0_u32..0x1CC7_u32,
  ]

  # SUNUWAR
  SUNUWAR = [
    0x11BC0_u32..0x11BE1_u32,
    0x11BF0_u32..0x11BF9_u32,
  ]

  # SYLOTI NAGRI
  SYLOTI_NAGRI = [
    0xA800_u32..0xA82C_u32,
  ]

  # SYRIAC
  SYRIAC = [
    0x700_u32..0x70D_u32,
    0x70F_u32..0x74A_u32,
    0x74D_u32..0x74F_u32,
    0x860_u32..0x86A_u32,
  ]

  # TAGALOG
  TAGALOG = [
    0x1700_u32..0x1715_u32,
    0x171F_u32..0x171F_u32,
  ]

  # TAGBANWA
  TAGBANWA = [
    0x1760_u32..0x176C_u32,
    0x176E_u32..0x1770_u32,
    0x1772_u32..0x1773_u32,
  ]

  # TAI LE
  TAI_LE = [
    0x1950_u32..0x196D_u32,
    0x1970_u32..0x1974_u32,
  ]

  # TAI THAM
  TAI_THAM = [
    0x1A20_u32..0x1A5E_u32,
    0x1A60_u32..0x1A7C_u32,
    0x1A7F_u32..0x1A89_u32,
    0x1A90_u32..0x1A99_u32,
    0x1AA0_u32..0x1AAD_u32,
  ]

  # TAI VIET
  TAI_VIET = [
    0xAA80_u32..0xAAC2_u32,
    0xAADB_u32..0xAADF_u32,
  ]

  # TAKRI
  TAKRI = [
    0x11680_u32..0x116B9_u32,
    0x116C0_u32..0x116C9_u32,
  ]

  # TAMIL
  TAMIL = [
    0xB82_u32..0xB83_u32,
    0xB85_u32..0xB8A_u32,
    0xB8E_u32..0xB90_u32,
    0xB92_u32..0xB95_u32,
    0xB99_u32..0xB9A_u32,
    0xB9C_u32..0xB9C_u32,
    0xB9E_u32..0xB9F_u32,
    0xBA3_u32..0xBA4_u32,
    0xBA8_u32..0xBAA_u32,
    0xBAE_u32..0xBB9_u32,
    0xBBE_u32..0xBC2_u32,
    0xBC6_u32..0xBC8_u32,
    0xBCA_u32..0xBCD_u32,
    0xBD0_u32..0xBD0_u32,
    0xBD7_u32..0xBD7_u32,
    0xBE6_u32..0xBFA_u32,
    0x11FC0_u32..0x11FF1_u32,
    0x11FFF_u32..0x11FFF_u32,
  ]

  # TANGSA
  TANGSA = [
    0x16A70_u32..0x16ABE_u32,
    0x16AC0_u32..0x16AC9_u32,
  ]

  # TANGUT
  TANGUT = [
    0x16FE0_u32..0x16FE0_u32,
    0x17000_u32..0x187F7_u32,
    0x18800_u32..0x18AFF_u32,
    0x18D00_u32..0x18D08_u32,
  ]

  # TELUGU
  TELUGU = [
    0xC00_u32..0xC0C_u32,
    0xC0E_u32..0xC10_u32,
    0xC12_u32..0xC28_u32,
    0xC2A_u32..0xC39_u32,
    0xC3C_u32..0xC44_u32,
    0xC46_u32..0xC48_u32,
    0xC4A_u32..0xC4D_u32,
    0xC55_u32..0xC56_u32,
    0xC58_u32..0xC5A_u32,
    0xC5D_u32..0xC5D_u32,
    0xC60_u32..0xC63_u32,
    0xC66_u32..0xC6F_u32,
    0xC77_u32..0xC7F_u32,
  ]

  # THAANA
  THAANA = [
    0x780_u32..0x7B1_u32,
  ]

  # THAI
  THAI = [
    0xE01_u32..0xE3A_u32,
    0xE40_u32..0xE5B_u32,
  ]

  # TIBETAN
  TIBETAN = [
    0xF00_u32..0xF47_u32,
    0xF49_u32..0xF6C_u32,
    0xF71_u32..0xF97_u32,
    0xF99_u32..0xFBC_u32,
    0xFBE_u32..0xFCC_u32,
    0xFCE_u32..0xFD4_u32,
    0xFD9_u32..0xFDA_u32,
  ]

  # TIFINAGH
  TIFINAGH = [
    0x2D30_u32..0x2D67_u32,
    0x2D6F_u32..0x2D70_u32,
    0x2D7F_u32..0x2D7F_u32,
  ]

  # TIRHUTA
  TIRHUTA = [
    0x11480_u32..0x114C7_u32,
    0x114D0_u32..0x114D9_u32,
  ]

  # TODHRI
  TODHRI = [
    0x105C0_u32..0x105F3_u32,
  ]

  # TOTO
  TOTO = [
    0x1E290_u32..0x1E2AE_u32,
  ]

  # TULU TIGALARI
  TULU_TIGALARI = [
    0x11380_u32..0x11389_u32,
    0x1138B_u32..0x1138B_u32,
    0x1138E_u32..0x1138E_u32,
    0x11390_u32..0x113B5_u32,
    0x113B7_u32..0x113C0_u32,
    0x113C2_u32..0x113C2_u32,
    0x113C5_u32..0x113C5_u32,
    0x113C7_u32..0x113CA_u32,
    0x113CC_u32..0x113D5_u32,
    0x113D7_u32..0x113D8_u32,
    0x113E1_u32..0x113E2_u32,
  ]

  # UGARITIC
  UGARITIC = [
    0x10380_u32..0x1039D_u32,
    0x1039F_u32..0x1039F_u32,
  ]

  # VAI
  VAI = [
    0xA500_u32..0xA62B_u32,
  ]

  # VITHKUQI
  VITHKUQI = [
    0x10570_u32..0x1057A_u32,
    0x1057C_u32..0x1058A_u32,
    0x1058C_u32..0x10592_u32,
    0x10594_u32..0x10595_u32,
    0x10597_u32..0x105A1_u32,
    0x105A3_u32..0x105B1_u32,
    0x105B3_u32..0x105B9_u32,
    0x105BB_u32..0x105BC_u32,
  ]

  # WANCHO
  WANCHO = [
    0x1E2C0_u32..0x1E2F9_u32,
    0x1E2FF_u32..0x1E2FF_u32,
  ]

  # WARANG CITI
  WARANG_CITI = [
    0x118A0_u32..0x118F2_u32,
    0x118FF_u32..0x118FF_u32,
  ]

  # YEZIDI
  YEZIDI = [
    0x10E80_u32..0x10EA9_u32,
    0x10EAB_u32..0x10EAD_u32,
    0x10EB0_u32..0x10EB1_u32,
  ]

  # YI
  YI = [
    0xA000_u32..0xA48C_u32,
    0xA490_u32..0xA4C6_u32,
  ]

  # ZANABAZAR SQUARE
  ZANABAZAR_SQUARE = [
    0x11A00_u32..0x11A47_u32,
  ]

  # Mapping from normalized property names to range arrays
  BY_NAME = {
    "adlam"                 => ADLAM,
    "ahom"                  => AHOM,
    "anatolianhieroglyphs"  => ANATOLIAN_HIEROGLYPHS,
    "arabic"                => ARABIC,
    "armenian"              => ARMENIAN,
    "avestan"               => AVESTAN,
    "balinese"              => BALINESE,
    "bamum"                 => BAMUM,
    "bassavah"              => BASSA_VAH,
    "batak"                 => BATAK,
    "bengali"               => BENGALI,
    "bhaiksuki"             => BHAIKSUKI,
    "bopomofo"              => BOPOMOFO,
    "brahmi"                => BRAHMI,
    "braille"               => BRAILLE,
    "buginese"              => BUGINESE,
    "buhid"                 => BUHID,
    "canadianaboriginal"    => CANADIAN_ABORIGINAL,
    "carian"                => CARIAN,
    "caucasianalbanian"     => CAUCASIAN_ALBANIAN,
    "chakma"                => CHAKMA,
    "cham"                  => CHAM,
    "cherokee"              => CHEROKEE,
    "chorasmian"            => CHORASMIAN,
    "common"                => COMMON,
    "coptic"                => COPTIC,
    "cuneiform"             => CUNEIFORM,
    "cypriot"               => CYPRIOT,
    "cyprominoan"           => CYPRO_MINOAN,
    "cyrillic"              => CYRILLIC,
    "deseret"               => DESERET,
    "devanagari"            => DEVANAGARI,
    "divesakuru"            => DIVES_AKURU,
    "dogra"                 => DOGRA,
    "duployan"              => DUPLOYAN,
    "egyptianhieroglyphs"   => EGYPTIAN_HIEROGLYPHS,
    "elbasan"               => ELBASAN,
    "elymaic"               => ELYMAIC,
    "ethiopic"              => ETHIOPIC,
    "garay"                 => GARAY,
    "georgian"              => GEORGIAN,
    "glagolitic"            => GLAGOLITIC,
    "gothic"                => GOTHIC,
    "grantha"               => GRANTHA,
    "greek"                 => GREEK,
    "gujarati"              => GUJARATI,
    "gunjalagondi"          => GUNJALA_GONDI,
    "gurmukhi"              => GURMUKHI,
    "gurungkhema"           => GURUNG_KHEMA,
    "han"                   => HAN,
    "hangul"                => HANGUL,
    "hanifirohingya"        => HANIFI_ROHINGYA,
    "hanunoo"               => HANUNOO,
    "hatran"                => HATRAN,
    "hebrew"                => HEBREW,
    "hiragana"              => HIRAGANA,
    "imperialaramaic"       => IMPERIAL_ARAMAIC,
    "inherited"             => INHERITED,
    "inscriptionalpahlavi"  => INSCRIPTIONAL_PAHLAVI,
    "inscriptionalparthian" => INSCRIPTIONAL_PARTHIAN,
    "javanese"              => JAVANESE,
    "kaithi"                => KAITHI,
    "kannada"               => KANNADA,
    "katakana"              => KATAKANA,
    "kawi"                  => KAWI,
    "kayahli"               => KAYAH_LI,
    "kharoshthi"            => KHAROSHTHI,
    "khitansmallscript"     => KHITAN_SMALL_SCRIPT,
    "khmer"                 => KHMER,
    "khojki"                => KHOJKI,
    "khudawadi"             => KHUDAWADI,
    "kiratrai"              => KIRAT_RAI,
    "lao"                   => LAO,
    "latin"                 => LATIN,
    "lepcha"                => LEPCHA,
    "limbu"                 => LIMBU,
    "lineara"               => LINEAR_A,
    "linearb"               => LINEAR_B,
    "lisu"                  => LISU,
    "lycian"                => LYCIAN,
    "lydian"                => LYDIAN,
    "mahajani"              => MAHAJANI,
    "makasar"               => MAKASAR,
    "malayalam"             => MALAYALAM,
    "mandaic"               => MANDAIC,
    "manichaean"            => MANICHAEAN,
    "marchen"               => MARCHEN,
    "masaramgondi"          => MASARAM_GONDI,
    "medefaidrin"           => MEDEFAIDRIN,
    "meeteimayek"           => MEETEI_MAYEK,
    "mendekikakui"          => MENDE_KIKAKUI,
    "meroiticcursive"       => MEROITIC_CURSIVE,
    "meroitichieroglyphs"   => MEROITIC_HIEROGLYPHS,
    "miao"                  => MIAO,
    "modi"                  => MODI,
    "mongolian"             => MONGOLIAN,
    "mro"                   => MRO,
    "multani"               => MULTANI,
    "myanmar"               => MYANMAR,
    "nabataean"             => NABATAEAN,
    "nagmundari"            => NAG_MUNDARI,
    "nandinagari"           => NANDINAGARI,
    "newtailue"             => NEW_TAI_LUE,
    "newa"                  => NEWA,
    "nko"                   => NKO,
    "nushu"                 => NUSHU,
    "nyiakengpuachuehmong"  => NYIAKENG_PUACHUE_HMONG,
    "ogham"                 => OGHAM,
    "olchiki"               => OL_CHIKI,
    "olonal"                => OL_ONAL,
    "oldhungarian"          => OLD_HUNGARIAN,
    "olditalic"             => OLD_ITALIC,
    "oldnortharabian"       => OLD_NORTH_ARABIAN,
    "oldpermic"             => OLD_PERMIC,
    "oldpersian"            => OLD_PERSIAN,
    "oldsogdian"            => OLD_SOGDIAN,
    "oldsoutharabian"       => OLD_SOUTH_ARABIAN,
    "oldturkic"             => OLD_TURKIC,
    "olduyghur"             => OLD_UYGHUR,
    "oriya"                 => ORIYA,
    "osage"                 => OSAGE,
    "osmanya"               => OSMANYA,
    "pahawhhmong"           => PAHAWH_HMONG,
    "palmyrene"             => PALMYRENE,
    "paucinhau"             => PAU_CIN_HAU,
    "phagspa"               => PHAGS_PA,
    "phoenician"            => PHOENICIAN,
    "psalterpahlavi"        => PSALTER_PAHLAVI,
    "rejang"                => REJANG,
    "runic"                 => RUNIC,
    "samaritan"             => SAMARITAN,
    "saurashtra"            => SAURASHTRA,
    "sharada"               => SHARADA,
    "shavian"               => SHAVIAN,
    "siddham"               => SIDDHAM,
    "signwriting"           => SIGNWRITING,
    "sinhala"               => SINHALA,
    "sogdian"               => SOGDIAN,
    "sorasompeng"           => SORA_SOMPENG,
    "soyombo"               => SOYOMBO,
    "sundanese"             => SUNDANESE,
    "sunuwar"               => SUNUWAR,
    "sylotinagri"           => SYLOTI_NAGRI,
    "syriac"                => SYRIAC,
    "tagalog"               => TAGALOG,
    "tagbanwa"              => TAGBANWA,
    "taile"                 => TAI_LE,
    "taitham"               => TAI_THAM,
    "taiviet"               => TAI_VIET,
    "takri"                 => TAKRI,
    "tamil"                 => TAMIL,
    "tangsa"                => TANGSA,
    "tangut"                => TANGUT,
    "telugu"                => TELUGU,
    "thaana"                => THAANA,
    "thai"                  => THAI,
    "tibetan"               => TIBETAN,
    "tifinagh"              => TIFINAGH,
    "tirhuta"               => TIRHUTA,
    "todhri"                => TODHRI,
    "toto"                  => TOTO,
    "tulutigalari"          => TULU_TIGALARI,
    "ugaritic"              => UGARITIC,
    "vai"                   => VAI,
    "vithkuqi"              => VITHKUQI,
    "wancho"                => WANCHO,
    "warangciti"            => WARANG_CITI,
    "yezidi"                => YEZIDI,
    "yi"                    => YI,
    "zanabazarsquare"       => ZANABAZAR_SQUARE,
  }
end
