require "./spec_helper"

def print_ast(pattern : String, *, unicode : Bool = true, ignore_whitespace : Bool = false, octal : Bool = false) : String
  ast = Regex::Syntax::AstParser.new(
    unicode: unicode,
    ignore_whitespace: ignore_whitespace,
    octal: octal
  ).parse(pattern)
  ast.to_s
end

describe Regex::Syntax::AST::Printer do
  it "prints literals and escapes from the AST surface it preserves" do
    print_ast("a").should eq("a")
    print_ast(%q(\[)).should eq(%q(\[))
    print_ast(%q(\141), octal: true).should eq(%q(\141))
    print_ast(%q(\x61)).should eq(%q(\x61))
    print_ast(%q(\x7F)).should eq(%q(\x7F))
    print_ast(%q(\x41)).should eq(%q(\x41))
    print_ast(%q(\u0061)).should eq(%q(\u0061))
    print_ast(%q(\U00000061)).should eq(%q(\U00000061))
    print_ast(%q(\x{61})).should eq(%q(\x{61}))
    print_ast(%q(\x{7F})).should eq(%q(\x{7F}))
    print_ast(%q(\u{61})).should eq(%q(\u{61}))
    print_ast(%q(\U{61})).should eq(%q(\U{61}))
    print_ast(%q(\u03A9)).should eq(%q(\u03A9))
    print_ast(%q(\U0001F600)).should eq(%q(\U0001F600))
    print_ast(%q(\a)).should eq(%q(\a))
    print_ast(%q(\f)).should eq(%q(\f))
    print_ast(%q(\t)).should eq(%q(\t))
    print_ast(%q(\n)).should eq(%q(\n))
    print_ast(%q(\r)).should eq(%q(\r))
    print_ast(%q(\v)).should eq(%q(\v))
    print_ast(%q((?x)\ )).should eq(%q((?x)\ ))
  end

  it "prints dot, concat, and alternation" do
    print_ast(".").should eq(".")
    print_ast("ab").should eq("ab")
    print_ast("abcde").should eq("abcde")
    print_ast("a|b").should eq("a|b")
    print_ast("a|b|c").should eq("a|b|c")
    print_ast("a|b|c|d|e").should eq("a|b|c|d|e")
    print_ast("|a|b|c|d|e").should eq("|a|b|c|d|e")
    print_ast("|a|b|c|d|e|").should eq("|a|b|c|d|e|")
    print_ast("a(bcd)ef").should eq("a(bcd)ef")
    print_ast("a(b|c|d)|e|f").should eq("a(b|c|d)|e|f")
  end

  it "prints assertions and repetitions" do
    print_ast("^").should eq("^")
    print_ast("$").should eq("$")
    print_ast(%q(\A)).should eq(%q(\A))
    print_ast(%q(\z)).should eq(%q(\z))
    print_ast(%q(\Z)).should eq(%q(\Z))
    print_ast(%q(\b)).should eq(%q(\b))
    print_ast(%q(\B)).should eq(%q(\B))
    print_ast(%q(\b{start})).should eq(%q(\b{start}))
    print_ast(%q(\b{end})).should eq(%q(\b{end}))
    print_ast(%q(\b{start-half})).should eq(%q(\b{start-half}))
    print_ast(%q(\b{end-half})).should eq(%q(\b{end-half}))
    print_ast(%q(\<)).should eq(%q(\<))
    print_ast(%q(\>)).should eq(%q(\>))
    print_ast("a?").should eq("a?")
    print_ast("a??").should eq("a??")
    print_ast("a*").should eq("a*")
    print_ast("a*?").should eq("a*?")
    print_ast("a+").should eq("a+")
    print_ast("a+?").should eq("a+?")
    print_ast("a{5}").should eq("a{5}")
    print_ast("a{5}?").should eq("a{5}?")
    print_ast("a{5,}").should eq("a{5,}")
    print_ast("a{5,}?").should eq("a{5,}?")
    print_ast("a{5,10}").should eq("a{5,10}")
    print_ast("a{5,10}?").should eq("a{5,10}?")
  end

  it "prints flags and groups" do
    print_ast("(?i)").should eq("(?i)")
    print_ast("(?-i)").should eq("(?-i)")
    print_ast("(?s-i)").should eq("(?s-i)")
    print_ast("(?-si)").should eq("(?-si)")
    print_ast("(?siUmux)").should eq("(?siUmux)")
    print_ast("(?i:a)").should eq("(?i:a)")
    print_ast("(?P<foo>a)").should eq("(?P<foo>a)")
    print_ast("(?<foo>a)").should eq("(?P<foo>a)")
    print_ast("(a)").should eq("(a)")
    print_ast("(?:a)").should eq("(?:a)")
  end

  it "prints classes from the current AST model" do
    print_ast("[abc]").should eq("[abc]")
    print_ast("[a-z]").should eq("[a-z]")
    print_ast("[^a-z]").should eq("[^a-z]")
    print_ast("[a-z0-9]").should eq("[a-z0-9]")
    print_ast("[-a-z0-9]").should eq("[-a-z0-9]")
    print_ast("[a-z0-9---]").should eq("[a-z0-9---]")
    print_ast("[a-z&&m-n]").should eq("[a-z&&m-n]")
    print_ast("[a-z--m-n]").should eq("[a-z--m-n]")
    print_ast("[a-z~~m-n]").should eq("[a-z~~m-n]")
    print_ast("[a-z[0-9]]").should eq("[a-z[0-9]]")
    print_ast("[[a-z&&m-n]]").should eq("[[a-z&&m-n]]")
    print_ast("[a-z[^0-9]]").should eq("[a-z[^0-9]]")
    print_ast(%q(\d)).should eq(%q(\d))
    print_ast(%q(\D)).should eq(%q(\D))
    print_ast(%q(\s)).should eq(%q(\s))
    print_ast(%q(\S)).should eq(%q(\S))
    print_ast(%q(\w)).should eq(%q(\w))
    print_ast(%q(\W)).should eq(%q(\W))
    print_ast("[[:alnum:]]").should eq("[[:alnum:]]")
    print_ast("[[:^alnum:]]").should eq("[[:^alnum:]]")
    print_ast("[[:alpha:]]").should eq("[[:alpha:]]")
    print_ast("[[:^alpha:]]").should eq("[[:^alpha:]]")
    print_ast("[[:ascii:]]").should eq("[[:ascii:]]")
    print_ast("[[:^ascii:]]").should eq("[[:^ascii:]]")
    print_ast("[[:blank:]]").should eq("[[:blank:]]")
    print_ast("[[:^blank:]]").should eq("[[:^blank:]]")
    print_ast("[[:cntrl:]]").should eq("[[:cntrl:]]")
    print_ast("[[:^cntrl:]]").should eq("[[:^cntrl:]]")
    print_ast("[[:digit:]]").should eq("[[:digit:]]")
    print_ast("[[:^digit:]]").should eq("[[:^digit:]]")
    print_ast("[[:graph:]]").should eq("[[:graph:]]")
    print_ast("[[:^graph:]]").should eq("[[:^graph:]]")
    print_ast("[[:lower:]]").should eq("[[:lower:]]")
    print_ast("[[:^lower:]]").should eq("[[:^lower:]]")
    print_ast("[[:print:]]").should eq("[[:print:]]")
    print_ast("[[:^print:]]").should eq("[[:^print:]]")
    print_ast("[[:punct:]]").should eq("[[:punct:]]")
    print_ast("[[:^punct:]]").should eq("[[:^punct:]]")
    print_ast("[[:space:]]").should eq("[[:space:]]")
    print_ast("[[:^space:]]").should eq("[[:^space:]]")
    print_ast("[[:upper:]]").should eq("[[:upper:]]")
    print_ast("[[:^upper:]]").should eq("[[:^upper:]]")
    print_ast("[[:word:]]").should eq("[[:word:]]")
    print_ast("[[:^word:]]").should eq("[[:^word:]]")
    print_ast("[[:xdigit:]]").should eq("[[:xdigit:]]")
    print_ast("[[:^xdigit:]]").should eq("[[:^xdigit:]]")
    print_ast(%q(\pL)).should eq(%q(\pL))
    print_ast(%q(\PL)).should eq(%q(\PL))
    print_ast(%q(\p{Greek})).should eq(%q(\p{Greek}))
    print_ast(%q(\P{sc:Greek})).should eq(%q(\P{sc:Greek}))
  end
end
